sonar.projectKey=spring-boot
sonar.projectName=Spring boot app for product
sonar.host.url=http://localhost:9000
sonar.login=squ_6ff43904a234a7ed37eec57b8d9d3656e0869b0c
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
# Include test coverage
sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPaths=target/jacoco.exec